### ISSUE TITLE
Hey brother, I am working on this project. Could you please provide the dataset? I would be grateful if you could

### ISSUE THREAD

**Issue by Jagdish2004** [IDinsight/hindi-fuzzy-merge#2]

**Comment by jeenut27** [comment]
Hi @Jagdish2004, thanks for reaching out! Unfortunately, we can't share the original data because of privacy and data sharing constraints. 

The idea used here to rely on multiple fuzzy matching techniques in decreasing order of their reliability to match 2 datasets can be used with any data. Hopefully this code can serve as a reference for setting up something similar with data you are working with. Let us know if you have questions!

**Comment by Jagdish2004** [comment]
Thanks for you response your code helped me a lot. :)
